Aishwarya Velumani
FE C Comp
119A1005

Q1

In [24]:
import pandas as pd
import numpy as np
from sklearn import datasets,svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [25]:
from google.colab import files
uploaded= files.upload()

Saving Churn_Modelling.csv to Churn_Modelling (3).csv


In [26]:
ds=pd.read_csv("Churn_Modelling.csv")
x=ds.iloc[:,:-1]
y=ds.iloc[:,7]
print(x)
print(y)

     Geography  Gender  Age  ...  HasCrCard  IsActiveMember  EstimatedSalary
0       France  Female   42  ...          1               1        101348.88
1        Spain  Female   41  ...          0               1        112542.58
2       France  Female   42  ...          1               0        113931.57
3       France  Female   39  ...          0               0         93826.63
4        Spain  Female   43  ...          1               1         79084.10
...        ...     ...  ...  ...        ...             ...              ...
9995    France    Male   39  ...          1               0         96270.64
9996    France    Male   35  ...          1               1        101699.77
9997    France  Female   36  ...          0               1         42085.58
9998   Germany    Male   42  ...          1               0         92888.52
9999    France  Female   28  ...          1               0         38190.78

[10000 rows x 7 columns]
0       1
1       0
2       1
3       0
4       0


In [27]:
geo=pd.get_dummies(x['Geography'],drop_first=True)
print(geo)

      Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]


In [28]:
gen=pd.get_dummies(x['Gender'],drop_first=True)
print(gen)

      Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]


In [29]:
x.drop(['Gender','Geography'],axis=1,inplace=True)
print(x)

      Age    Balance  HasCrCard  IsActiveMember  EstimatedSalary
0      42       0.00          1               1        101348.88
1      41   83807.86          0               1        112542.58
2      42  159660.80          1               0        113931.57
3      39       0.00          0               0         93826.63
4      43  125510.82          1               1         79084.10
...   ...        ...        ...             ...              ...
9995   39       0.00          1               0         96270.64
9996   35   57369.61          1               1        101699.77
9997   36       0.00          0               1         42085.58
9998   42   75075.31          1               0         92888.52
9999   28  130142.79          1               0         38190.78

[10000 rows x 5 columns]


In [30]:
x=pd.concat([x,gen,geo],axis=1)
print(x)

      Age    Balance  HasCrCard  ...  Male  Germany  Spain
0      42       0.00          1  ...     0        0      0
1      41   83807.86          0  ...     0        0      1
2      42  159660.80          1  ...     0        0      0
3      39       0.00          0  ...     0        0      0
4      43  125510.82          1  ...     0        0      1
...   ...        ...        ...  ...   ...      ...    ...
9995   39       0.00          1  ...     1        0      0
9996   35   57369.61          1  ...     1        0      0
9997   36       0.00          0  ...     0        0      0
9998   42   75075.31          1  ...     1        1      0
9999   28  130142.79          1  ...     0        0      0

[10000 rows x 8 columns]


In [31]:
x.isnull().sum()

Age                0
Balance            0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Male               0
Germany            0
Spain              0
dtype: int64

In [32]:
xtr,xte,ytr,yte= train_test_split(x,y,test_size=0.3,random_state=0)
sc=StandardScaler()
xtr=sc.fit_transform(xtr)
xte=sc.fit_transform(xte)

In [33]:
cls=svm.SVC()
cls.fit(xtr,ytr)
ypr=cls.predict(xte)

In [34]:
print(yte)
print(ypr)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
4004    0
7375    0
9307    0
8394    0
5233    1
Name: Exited, Length: 3000, dtype: int64
[0 0 0 ... 0 0 0]


In [35]:
print('Percentage accuracy: ',100*accuracy_score(ypr,yte))

Percentage accuracy:  83.66666666666667


Q2

In [36]:
iri=datasets.load_iris()
x=iri.data
y=iri.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [40]:
from sklearn import tree
xtr,xte,ytr,yte=train_test_split(x,y,test_size=0.3,random_state=0)
dtc=tree.DecisionTreeClassifier()
dtc=dtc.fit(xtr,ytr)
ypr=dtc.predict(xte)

In [41]:
print(yte)
print(ypr)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0]


In [42]:
print("Decision tree accuracy: ",100*accuracy_score(yte,ypr))

Decision tree accuracy:  97.77777777777777


In [43]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(criterion='entropy',n_estimators=50,random_state=0,n_jobs=2)
rf.fit(xtr,ytr)
ypr=rf.predict(xte)
print(yte)
print(ypr)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0]


In [44]:
print("Random forest accuracy: ",100*accuracy_score(yte,ypr))

Random forest accuracy:  97.77777777777777
