<a href="https://colab.research.google.com/github/AishwaryaVelumani/Python-IP-ML/blob/master/Content_Based_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text= ["London Paris London","Paris Paris London"]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()
#to convert text to vectors
count_matrix= cv.fit_transform(text)
#fit_transform learns the vocabulary dictionary and returns document-term matrix

In [3]:
print(cv.get_feature_names())
print(count_matrix.toarray())
#toarray() is used to make the count_matrix human readable

['london', 'paris']
[[2 1]
 [1 2]]


In [4]:
type(count_matrix)

scipy.sparse.csr.csr_matrix

In [5]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores= cosine_similarity(count_matrix)
#to find the cosine similarity between vectors
print(similarity_scores)
#matrix of text x text, there is always a 1 in every row since every text is perfectly similar to itself

[[1.  0.8]
 [0.8 1. ]]


# Movie Dataset

In [6]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
from google.colab import files

In [8]:
uploaded= files.upload()

Saving movie_dataset.csv to movie_dataset.csv


In [9]:
ds= pd.read_csv('movie_dataset.csv',encoding='latin_1')

In [10]:
features= ['keywords','cast','genres','director']

In [11]:
def combine_features(row):
    return row['keywords']+' '+row['cast']+' '+row['genres']+' '+row['director']
#combine the values of these strings to a single string

In [19]:
for feature in features:
    ds[feature]= ds[feature].fillna('')

ds['combined_features']= ds.apply(combine_features,axis=1)
#applying combine_features function on each row and storing the resultant string in the corresponding row in the combined_features column

'culture clash future space war space colony society Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Action Adventure Fantasy Science Fiction James Cameron'

In [22]:
print(ds['combined_features'][1])
print(ds['keywords'][1])
print(ds['cast'][1])
print(ds['genres'][1])
print(ds['director'][1])

ocean drug abuse exotic island east india trading company love of one's life Johnny Depp Orlando Bloom Keira Knightley Stellan Skarsg\u00e5rd Chow Yun-fat Adventure Fantasy Action Gore Verbinski
ocean drug abuse exotic island east india trading company love of one's life
Johnny Depp Orlando Bloom Keira Knightley Stellan Skarsg\u00e5rd Chow Yun-fat
Adventure Fantasy Action
Gore Verbinski


In [23]:
cv= CountVectorizer()
count_matrix= cv.fit_transform(ds['combined_features'])

In [24]:
print(count_matrix)

  (0, 888)	1
  (0, 731)	1
  (0, 1412)	1
  (0, 3524)	2
  (0, 4048)	1
  (0, 771)	1
  (0, 3500)	1
  (0, 3282)	1
  (0, 4165)	1
  (0, 4218)	1
  (0, 3274)	1
  (0, 3448)	1
  (0, 4072)	1
  (0, 3584)	1
  (0, 2151)	1
  (0, 2514)	1
  (0, 3193)	1
  (0, 21)	1
  (0, 42)	1
  (0, 1266)	1
  (0, 3340)	1
  (0, 1301)	1
  (0, 1897)	1
  (0, 587)	1
  (1, 21)	1
  :	:
  (738, 1138)	1
  (738, 3046)	1
  (738, 3911)	1
  (738, 953)	1
  (738, 411)	1
  (738, 2696)	1
  (738, 934)	1
  (738, 2941)	1
  (739, 21)	1
  (739, 865)	1
  (739, 3747)	2
  (739, 3769)	1
  (739, 1392)	1
  (739, 1195)	1
  (739, 249)	1
  (739, 7)	1
  (739, 1134)	1
  (739, 1468)	1
  (739, 568)	1
  (739, 2277)	1
  (739, 2579)	1
  (739, 2483)	1
  (739, 139)	1
  (739, 336)	1
  (739, 2204)	1


In [25]:
cosine_sim= cosine_similarity(count_matrix)

In [26]:
print(cosine_sim)

[[1.         0.10540926 0.12038585 ... 0.03849002 0.         0.04303315]
 [0.10540926 1.         0.0761387  ... 0.10954451 0.         0.04082483]
 [0.12038585 0.0761387  1.         ... 0.04170288 0.08340577 0.09325048]
 ...
 [0.03849002 0.10954451 0.04170288 ... 1.         0.04       0.26832816]
 [0.         0.         0.08340577 ... 0.04       1.         0.        ]
 [0.04303315 0.04082483 0.09325048 ... 0.26832816 0.         1.        ]]


In [27]:
def get_title_from_index(index):
    return ds[ds.index==index]['title'].values[0]

def get_index_from_title(title):
    return ds[ds.title==title]['index'].values[0]

In [31]:
movie_user_likes= 'Avatar'
movie_index= get_index_from_title(movie_user_likes)
similar_movies= list(enumerate(cosine_sim[movie_index]))
#accessing the row of the all the similarity scores of a particular movie and then creating a list by enumerating over it

In [35]:
sorted_similar_movies= sorted(similar_movies,key= lambda x:x[1], reverse=True) [1:]
#reverse means in descending order
#[1:]: removing the first suggested movie because it will be the input movie itself(a movie will be the most similar movie of itself)

In [37]:
i=0
print("Top 5 similar movies to "+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>10:
        break

Top 5 similar movies to Avatar are:

Guardians of the Galaxy
Star Trek Into Darkness
Star Trek Beyond
Planet of the Apes
Gravity
Jupiter Ascending
The Wolverine
Zathura: A Space Adventure
Star Trek
Lost in Space
The Fifth Element
