In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print(a[1])
print(a[-2])

2
9


In [15]:
print(a[1:])

[ 2  3  4  5  6  7  8  9 10]


In [5]:
print(a[:-1])

[1 2 3 4 5 6 7 8 9]


In [6]:
print(a[2:7:2])

[3 5 7]


In [8]:
print(a[[1,-2,3]])

[2 9 4]


In [9]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [10]:
print(b[0,1])

2


In [13]:
print(b[1,:2])

[4 5]


In [16]:
print(b+2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
print(np.square(b))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
c=b**3
print(c)

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [23]:
d=np.power(c,b)
print(d)

[[                   1                   64                19683]
 [            16777216          30517578125      101559956668416]
 [  558545864083284007                    0 -8127490854706933095]]


In [21]:
512**64

247330401473104534060502521019647190035131349101211839914063056092897225106531867170316401061243044989597671426016139339351365034306751209967546155101893167916606772148699136

In [22]:
729**81

7602033756829688179535612101927342434798006222913345882096671718462026450847558385638399133044640009857513126790996106341658482736771462692522663416083613709397190583473914100243037919870652143046001421207236044960360057945209303129

In [24]:
print(c)

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [25]:
print(np.max(c))

729


In [26]:
print(np.sum(c))

2025
