In [1]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
type(b)


[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [ ]:
c=np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
type(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


numpy.ndarray

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(6,)
(2, 3)
(2, 2, 3)


In [ ]:
d=np.array([[1],[2],[3],[4],[5],[6]])
print(d)
print(d.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [ ]:
print(c.ndim)

3


In [ ]:
print(b.dtype)

int64


In [ ]:
e=np.array([1,2,4],dtype=float)

In [ ]:
print(e.dtype)

float64


In [ ]:
f=np.array(['a','b','c'])
print(f.dtype)

<U1


In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b1=b.reshape(1,6)
print(b1)

[[1 2 3 4 5 6]]


In [ ]:
b2=b.reshape(3,2)
print(b2)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [4]:
b=np.linspace(1,10,4)
print(b)

[ 1.  4.  7. 10.]


In [6]:
c=np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
d=np.ones((1,2))
d

array([[1., 1.]])

In [8]:
type(d)

numpy.ndarray

In [9]:
type(d[0][1])

numpy.float64

In [10]:
e=np.eye(2,dtype=float)
e

array([[1., 0.],
       [0., 1.]])

In [11]:
print(np.random.rand(2,2))

[[0.84018218 0.59064462]
 [0.82518326 0.18892006]]


In [12]:
print(np.random.randn(2,2))

[[-0.18719829 -0.74589767]
 [-1.35638691 -1.08808119]]


In [18]:
f=np.random.randint(7,size=(2,2))
print(f)

[[3 2]
 [3 5]]


In [19]:
print(f.max())

5
