<a href="https://colab.research.google.com/github/AishwaryaVelumani/Python-IP-ML/blob/master/Simple_Ensemble_Techniques_Max_Vote%2C_Average%2C_Weighted_Average.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

from scipy import stats

In [25]:
iri= datasets.load_iris()
x,y= iri.data,iri.target

In [26]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [27]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [28]:
xtr,xte,ytr,yte= train_test_split(x,y,test_size=0.3,random_state=0)

#Logistic Regression
lr= LogisticRegression()
lr.fit(xtr,ytr)
ypr_lr= lr.predict(xte)

#KNN
sc= StandardScaler()
sc.fit(x)
scaled_features= sc.transform(x)
xtr,xte,ytr,yte =train_test_split(scaled_features,y,test_size=0.3,random_state=0)
knn= KNeighborsClassifier(n_neighbors=3,metric='euclidean')
knn.fit(xtr,ytr)
ypr_knn= knn.predict(xte)

#Decision Tree
xtr,xte,ytr,yte= train_test_split(x,y,test_size=0.3,random_state=0)
dt= DecisionTreeClassifier()
dt.fit(xtr,ytr)
ypr_dt= dt.predict(xte)


# Max Vote

In [29]:
final_pred= np.array([])
for i in range(0,len(xte)):
    final_pred= np.append(final_pred, stats.mode([ypr_lr[i],ypr_knn[i],ypr_dt[i]]))
print(final_pred)

[2. 3. 1. 3. 0. 3. 2. 3. 0. 3. 2. 3. 0. 3. 1. 3. 1. 3. 1. 3. 2. 3. 1. 3.
 1. 3. 1. 3. 1. 3. 0. 3. 1. 3. 1. 3. 0. 3. 0. 3. 2. 3. 1. 3. 0. 3. 0. 3.
 2. 3. 0. 3. 0. 3. 1. 3. 1. 3. 0. 3. 2. 3. 1. 3. 0. 3. 2. 3. 2. 3. 1. 3.
 0. 3. 2. 3. 1. 3. 1. 3. 2. 3. 0. 3. 2. 3. 0. 3. 0. 3.]


In [30]:
from sklearn.ensemble import VotingClassifier
vc= VotingClassifier(estimators=[('lr',lr),('dt',dt),('knn',knn)],voting='hard')
vc.fit(xtr,ytr)
vc.score(xte,yte)

0.9777777777777777

# Average

In [42]:
ypr_lr= lr.predict_proba(xte)
ypr_knn= knn.predict_proba(xte)
ypr_dt= dt.predict_proba(xte)
#print(ypr_dt)
#print(xte)

final_pred= (ypr_lr+ypr_knn+ypr_dt)/3
print(final_pred.shape)

(45, 3)


# Weighted Average

In [44]:
final_pred= ypr_lr*0.3 + ypr_knn*0.3 + ypr_dt*0.4
print(final_pred.shape)

(45, 3)
